#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pywavelets
Version  : 1.3.0
Release  : 49
URL      : https://files.pythonhosted.org/packages/32/ab/b96b19cae562aecaa57f0cdb501be169a38ec685ddcc91f1de20f849b22e/PyWavelets-1.3.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/32/ab/b96b19cae562aecaa57f0cdb501be169a38ec685ddcc91f1de20f849b22e/PyWavelets-1.3.0.tar.gz
Summary  : PyWavelets, wavelet transform module
Group    : Development/Tools
License  : MIT
Requires: pypi-pywavelets-filemap = %{version}-%{release}
Requires: pypi-pywavelets-lib = %{version}-%{release}
Requires: pypi-pywavelets-license = %{version}-%{release}
Requires: pypi-pywavelets-python = %{version}-%{release}
Requires: pypi-pywavelets-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cython)
BuildRequires : pypi(docutils)
BuildRequires : pypi(matplotlib)
BuildRequires : pypi(numpy)
BuildRequires : pypi(numpydoc)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
BuildRequires : pypi-cython

%description
+---------------+-----------------+
| Service       | Master branch   |
+===============+=================+
| Travis        | |travis_ci|     |
+---------------+-----------------+
| Appveyor      | |appveyor_ci|   |
+---------------+-----------------+
| Read the Docs | |read_the_docs| |
+---------------+-----------------+

%package filemap
Summary: filemap components for the pypi-pywavelets package.
Group: Default

%description filemap
filemap components for the pypi-pywavelets package.


%package lib
Summary: lib components for the pypi-pywavelets package.
Group: Libraries
Requires: pypi-pywavelets-license = %{version}-%{release}
Requires: pypi-pywavelets-filemap = %{version}-%{release}

%description lib
lib components for the pypi-pywavelets package.


%package license
Summary: license components for the pypi-pywavelets package.
Group: Default

%description license
license components for the pypi-pywavelets package.


%package python
Summary: python components for the pypi-pywavelets package.
Group: Default
Requires: pypi-pywavelets-python3 = %{version}-%{release}

%description python
python components for the pypi-pywavelets package.


%package python3
Summary: python3 components for the pypi-pywavelets package.
Group: Default
Requires: pypi-pywavelets-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(pywavelets)
Requires: pypi(docutils)
Requires: pypi(matplotlib)
Requires: pypi(numpy)
Requires: pypi(numpydoc)

%description python3
python3 components for the pypi-pywavelets package.


%prep
%setup -q -n PyWavelets-1.3.0
cd %{_builddir}/PyWavelets-1.3.0
pushd ..
cp -a PyWavelets-1.3.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656403172
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pywavelets
cp %{_builddir}/PyWavelets-1.3.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pywavelets/5281e9c932bfeeb26d9b74e98d9deecd806816a0
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-pywavelets

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pywavelets/5281e9c932bfeeb26d9b74e98d9deecd806816a0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
