#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pywavelets
Version  : 1.2.0
Release  : 43
URL      : https://files.pythonhosted.org/packages/35/e9/decd467448cde227aad94ff2976046afd3a51ad461ba9a325840687e8836/PyWavelets-1.2.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/35/e9/decd467448cde227aad94ff2976046afd3a51ad461ba9a325840687e8836/PyWavelets-1.2.0.tar.gz
Summary  : PyWavelets, wavelet transform module
Group    : Development/Tools
License  : MIT
Requires: pypi-pywavelets-license = %{version}-%{release}
Requires: pypi-pywavelets-python = %{version}-%{release}
Requires: pypi-pywavelets-python3 = %{version}-%{release}
BuildRequires : Cython
BuildRequires : buildreq-distutils3
Provides: PyWavelets
Provides: PyWavelets-python
Provides: PyWavelets-python3
BuildRequires : pypi(cython)
BuildRequires : pypi(docutils)
BuildRequires : pypi(matplotlib)
BuildRequires : pypi(numpy)
BuildRequires : pypi(numpydoc)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
+---------------+-----------------+
| Service       | Master branch   |
+===============+=================+
| Travis        | |travis_ci|     |
+---------------+-----------------+
| Appveyor      | |appveyor_ci|   |
+---------------+-----------------+
| Read the Docs | |read_the_docs| |
+---------------+-----------------+

%package license
Summary: license components for the pypi-pywavelets package.
Group: Default

%description license
license components for the pypi-pywavelets package.


%package python
Summary: python components for the pypi-pywavelets package.
Group: Default
Requires: pypi-pywavelets-python3 = %{version}-%{release}

%description python
python components for the pypi-pywavelets package.


%package python3
Summary: python3 components for the pypi-pywavelets package.
Group: Default
Requires: python3-core
Provides: pypi(pywavelets)
Requires: pypi(docutils)
Requires: pypi(matplotlib)
Requires: pypi(numpy)
Requires: pypi(numpydoc)

%description python3
python3 components for the pypi-pywavelets package.


%prep
%setup -q -n PyWavelets-1.2.0
cd %{_builddir}/PyWavelets-1.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641486409
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pywavelets
cp %{_builddir}/PyWavelets-1.2.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-pywavelets/5281e9c932bfeeb26d9b74e98d9deecd806816a0
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pywavelets/5281e9c932bfeeb26d9b74e98d9deecd806816a0

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
